# Generated by Django 5.1.1 on 2024-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/nobody.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
