# Generated by Django 5.1.1 on 2024-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hall',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
