# Generated by Django 5.1.1 on 2024-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_remove_reservation_table_reservation_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
