# Generated by Django 5.1.1 on 2024-09-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_reservation_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='edited',
        ),
    ]
