# Generated by Django 5.1.1 on 2024-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_remove_reservation_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
