# Generated by Django 5.1.1 on 2024-09-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_alter_testimonial_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
