# Generated by Django 5.1.1 on 2024-09-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_alter_comment_options_comment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
