# Generated by Django 5.1.1 on 2024-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0011_alter_comment_content_alter_testimonial_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
