# Generated by Django 5.1.1 on 2024-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0012_testimonial_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
